spring:
  datasource:
    url: jdbc:postgresql://34.133.108.157:5432/${var.database.name}?schema=${var.database.schema}
    username: appjaipro
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5