spring:
  datasource:
    url: jdbc:postgresql://35.188.213.65:5432/${var.database.name}?schema=${var.database.schema}
    username: appjaipro_dev
    password: ${DB_PWD_DEV}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

var:
  database:
    name: jaipro_dev
    schema: jaipro