INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('1', 'General', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('2', 'General', '2') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('3', 'General', '3') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('4', 'General', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('5', 'General', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('6', 'General', '6') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('7', 'General', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('8', 'General', '8') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('9', 'General', '9') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('10', 'General', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('11', 'General', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('12', 'General', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('13', 'General', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('14', 'General', '14') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('15', 'General', '15') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('16', 'General', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('17', 'Impermeabilización de Estructuras y Techos', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('18', 'Reparación de Muros atacados por Salitre o Eflorescencia', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('19', 'Diagnóstico y Reparación de Estructuras atacadas por Corrosión', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('20', 'Obras de saneamiento', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('21', 'Obras de Pavimentación', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('22', 'Enchapador de mayolicas', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('23', 'Tecnico en obra civil', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('24', 'Diseño de Planos', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('25', 'Saneamiento Físico Legal', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('26', 'Seguridad y Salud en el Trabajo', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('27', 'Servicios Generales', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('28', 'Arquitectura', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('29', 'Ingeniero', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('30', 'Hormigón Armado', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('31', 'Contratista', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('32', 'Drywall', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('33', 'Cielo raso', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('34', 'Cámaras de seguridad', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('35', 'Instalación de puertas y vantanas', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('36', 'Remodelación de viviendas', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('37', 'Ampliaciones de vivienda', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('38', 'Estructuras con Fibras de Carbono', '1') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('39', 'Pintura General', '2') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('40', 'Pintura decorativa', '2') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('41', 'Pintura en Altura', '2') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('42', 'Letrista', '2') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('43', 'Revestimientos', '2') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('44', 'Drywall', '2') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('45', 'Electricidad General', '3') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('46', 'Alarmas y seguridad', '3') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('47', 'Redes y Telefonia', '3') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('48', 'Energías Renovables', '3') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('49', 'Cableado Estructurado', '3') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('50', 'Eficiencia Energética', '3') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('51', 'Puesta a tierra', '3') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('52', 'Albañileria general', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('53', 'Yeseria', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('54', 'Colocación de revestimientos', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('55', 'Concreto reforzado', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('56', 'Enchapador', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('57', 'Tarrajeador', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('58', 'Servicios Generales', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('59', 'Piscinas', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('60', 'Drywall', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('61', 'Tabiqueria', '4') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('62', 'Oficinas', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('63', 'Diseño de oficinas', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('64', 'Restaurador', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('65', 'Vinilos', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('66', 'Diseño de interiores', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('67', 'Locales Comerciales', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('68', 'Remodelacion de interiores', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('69', 'Muebles de diseño', '5') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('70', 'Instalación', '6') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('71', 'Reparación', '6') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('72', 'Comercial', '6') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('73', 'Residencial', '6') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('74', 'Camaras de seguridad', '6') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('75', 'aire acondicionado y refrigeración', '6') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('76', 'Carpintería metálica', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('77', 'Tabiqueria', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('78', 'Fachadas', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('79', 'Técnico en Sistema Drywall', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('80', 'Drywall Arquitectonico', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('81', 'Casas en Drywall', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('82', 'Servicios De Pintura', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('83', 'Drywall en general.', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('84', 'Cielo Raso', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('85', 'Detalles y acabados en Drywall', '7') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('86', 'Calefaccionista', '8') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('87', 'Gasfiteria general', '8') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('88', 'Climatizacion de piscina.', '8') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('89', 'Tramites y habilitaciones', '8') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('90', 'Servicio tecnico de artefactos', '8') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('91', 'Muebles en hierro', '9') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('92', 'Rejas', '9') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('93', 'Herreria de Obra', '9') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('94', 'Cerramientos de balcones', '9') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('95', 'Escaleras y pasarelas', '9') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('96', 'Automatizacion de portones', '9') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('97', 'Sistemas de riego automático', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('98', 'Construcción de huertas', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('99', 'Diseño y construcción de jardines', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('100', 'Mantenimiento de jardines', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('101', 'Mantenimiento plantas oficinas', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('102', 'Jardines verticales', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('103', 'Estanques y fuentes', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('104', 'Podas en altura, raleos, descopes, talas  y extracciones.', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('105', 'Diseño con maceteria y plantas', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('106', 'Diseño en Balcones', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('107', 'Mantenimiento Piscinas', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('108', 'Paisajismo', '10') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('109', 'Ebanisteria', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('110', 'Restaurador', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('111', 'Muebles', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('112', 'Carpinteria General', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('113', 'Melamine', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('114', 'Carpinteria Metalica', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('115', 'Pisos', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('116', 'Drywall', '11') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('117', 'Redes y conectividad', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('118', 'Reparación de notebooks, laptops, netbooks', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('119', 'Impresoras', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('120', 'Asesoría y venta', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('121', 'Productos Apple', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('122', 'PC y Windows', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('123', 'Software y sitios web', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('124', 'Formateo de PC', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('125', 'Cableados de red', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('126', 'Camaras de seguridad', '12') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('127', 'Reparaciones', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('128', 'Nuevo', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('129', 'Techado asfaltico', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('130', 'Cabreadas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('131', 'Zingueria', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('132', 'Francesas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('133', 'Coloniales', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('134', 'Pizarras', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('135', 'Reformas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('136', 'Portuguesas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('137', 'Normandas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('138', 'Romanas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('139', 'Holandesas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('140', 'Metálicas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('141', 'Chapas', '13') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('142', 'Lavavajillas', '14') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('143', 'Secarropas', '14') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('144', 'Lavarropas', '14') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('145', 'Microondas', '14') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('146', 'Heladeras', '14') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('147', 'TV', '14') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('148', 'Consolas de videojuegos', '14') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('149', 'Costura', '15') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('150', 'Restauracion', '15') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('151', 'Lavado de muebles tapizados', '15') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('152', 'Carpinteria de Muebles Tapizados', '15') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('153', 'Fumigaciones', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('154', 'Limpieza de Cisterna, Tanque y Pozo Septico', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('155', 'Sistema contra incendios', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('156', 'Marmoleria', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('157', 'Seguridad y Salud en el Trabajo', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('158', 'Extintores', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('159', 'Consultor Agricola', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('160', 'Alfombras', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('161', 'Cortinas', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('162', 'Carpinteria en Aluminio', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('163', 'Técnico Antenas Satelital', '16') ON CONFLICT DO NOTHING;
INSERT INTO jaipro.specialization (specialization_id, name, profession_id) values ('164', 'Drywall', '16') ON CONFLICT DO NOTHING;